# Auto-generated by AiCopilot::AutoFixService.
# Stubs external HTTP endpoints so spec runs inside the fix loop don't hit real APIs.
if defined?(WebMock)
  include WebMock::API

  # opencode.ai/zen proxy
  stub_request(:post, %r{opencode\.ai/zen/v1/chat/completions})
    .to_return(
      status: 200,
      headers: { "Content-Type" => "application/json" },
      body: {
        id: "chatcmpl-autofix",
        object: "chat.completion",
        choices: [{
          index: 0,
          message: {
            role: "assistant",
            content: "Stubbed response from auto-fix network mock."
          },
          finish_reason: "stop"
        }],
        usage: { prompt_tokens: 10, completion_tokens: 10, total_tokens: 20 }
      }.to_json
    )

  # OpenAI embeddings endpoint
  stub_request(:post, %r{api\.openai\.com/v1/embeddings})
    .to_return(
      status: 200,
      headers: { "Content-Type" => "application/json" },
      body: {
        object: "list",
        data: [{ object: "embedding", index: 0, embedding: Array.new(1536, 0.01) }],
        model: "text-embedding-ada-002",
        usage: { prompt_tokens: 10, total_tokens: 10 }
      }.to_json
    )

  # Anthropic Claude API
  stub_request(:post, %r{api\.anthropic\.com/v1/messages})
    .to_return(
      status: 200,
      headers: { "Content-Type" => "application/json" },
      body: {
        id: "msg_autofix",
        type: "message",
        role: "assistant",
        content: [{ type: "text", text: "Stubbed response from auto-fix network mock." }],
        model: "claude-sonnet-4-6",
        usage: { input_tokens: 10, output_tokens: 10 }
      }.to_json
    )

  # OpenAI chat completions (non-opencode)
  stub_request(:post, %r{api\.openai\.com/v1/chat/completions})
    .to_return(
      status: 200,
      headers: { "Content-Type" => "application/json" },
      body: {
        id: "chatcmpl-autofix",
        object: "chat.completion",
        choices: [{
          index: 0,
          message: { role: "assistant", content: "Stubbed response." },
          finish_reason: "stop"
        }],
        usage: { prompt_tokens: 10, completion_tokens: 10, total_tokens: 20 }
      }.to_json
    )

  # Ollama local endpoint
  stub_request(:post, %r{localhost:11434})
    .to_return(
      status: 200,
      headers: { "Content-Type" => "application/json" },
      body: { message: { role: "assistant", content: "Stubbed response." } }.to_json
    )

  # Catch-all for any other external HTTP
  stub_request(:any, /(?:https?:\/\/)?[^:]*\.[^:]{2,}/)
    .to_return(status: 200, body: "Stubbed by auto-fix.")
    .with { |r| !r.uri.to_s.include?("localhost") && !r.uri.to_s.include?("127.0.0.1") }
end
